### ISSUE TITLE
Global support for undo/redo

### ISSUE THREAD

**Issue by Sheyne** [2graphic/sinap-ide#134]
Should intelligently include the graph editor, interleaving undo events from the OS with `Node` moves and whatnot.

**Comment by RighteousRaichu** [comment]
Working on this in: https://github.com/2graphic/sinap-ide/tree/undo-redo

**Comment by RighteousRaichu** [comment]
Some comments here: 422932d

**Comment by RighteousRaichu** [comment]
@CJ would it break anything to merge the listeners for creating and deleting nodes and edges, so we'd just have one listener for creating and deleting drawable elements?

Right now if say I delete a graph that contains nodes and edges, I'll get a change for the deleted nodes and a change for the deleted edges, and the graph controller has no way of knowing if that was one action or not for undoing.

**Comment by RighteousRaichu** [comment]
Also moving an edge still triggers two notifications instead of lumping them together.

**Comment by RighteousRaichu** [comment]
FYI @ilargierdi I'm working on this branch this afternoon

**Comment by ilargierdi** [comment]
I'm done working on it, unless there's something horribly wrong with my
changes that you need me to fix.

**Comment by RighteousRaichu** [comment]
@CJ I need you to look into a couple things:
* DrawableGraph keeps a list of _deleted elements, which is unacceptable because this can grow without bound.
* When you create two edges between nodes, such that they're curved, and delete one, the other one stays curved (this has been happening since your previous commit.)
* I had to do some hacky things to DrawableGraph to make this work, you may wanna change some stuff. IMO we may wanna rethink the events in 1.0 and leave it hacky for now.

**Comment by RighteousRaichu** [comment]
After beta we need to discuss a more powerful event infrastructure in order to clean up this code.
Also need to support undo'ing moving elements.
