### ISSUE TITLE
selectAll on graphEditor

### ISSUE THREAD

**Issue by RighteousRaichu** [2graphic/sinap-ide#162]
"Your function is working just fine. My guess is that the hidden text box is
capturing the Ctrl+A keybind and halting propagation natively."

This does work fine on macOS.

**Comment by ilargierdi** [comment]
It turns out that the `Ctrl+a` keybind doesn't even work on Windows. Directly using the `Select All` menu item works just fine, but trying to invoke the action from the keyboard on Windows doesn't even trigger the `clickHandlerMake` function. My guess is that the menu item has to be declared with a `role` field in order for it to work.

**Comment by Sheyne** [comment]
Is this still an issue?

**Comment by RighteousRaichu** [comment]
#315
