### ISSUE TITLE
Need a way to debug modals

### ISSUE THREAD

**Issue by slaymaker1907** [2graphic/sinap-ide#173]
Specifically, I'm trying to figure out what is wrong with my Angular template for the new modal dialog. However, I can't figure out how to even open up the console to see what went wrong.

**Comment by slaymaker1907** [comment]
In the main index.ts, you can comment out newWindow.setMenu(null as any), but I think we did not want to have that window which then enables developer tools.

That works for now, but I think we need a better longterm solution.

**Comment by RighteousRaichu** [comment]
On macOS we always have a menu, so I've just been using the shortcut. I suppose that without the menu the shortcut doesn't work?

**Comment by slaymaker1907** [comment]
Nope, it doesn't seem to work.

Also, even with the developer console, it looks like if a component fails to build in Angular, it just pretends like that component does not exist (so you don't get a helpful error message).

**Comment by RighteousRaichu** [comment]
I can't think of anything better other than just showing the menu during development, so instead of commenting it out do:
```
if (process.env.ENV === 'production') {
  newWindow.setMenu(null as any);
}
```

As far as the angular error messages, I'm not sure what you're doing, but if you throw an error while creating a component or the template can't be parsed angular definitely throws an error.

**Comment by slaymaker1907** [comment]
Can confirm that the second issue was just an issue between the ears.
