### ISSUE TITLE
Graph Editor - Select When Dragging

### ISSUE THREAD

**Issue by RighteousRaichu** [2graphic/sinap-ide#32]
I think it’d make sense if when dragging an element it selects it before. Currently it selects an element on mouseup when you’re done dragging. (Or, don't select an element if just dragging it.)

**Comment by ilargierdi** [comment]
Sheyne brought up something I hadn't thought about earlier today regarding multiple selected components. When moving one of a collection of selected components, the entire selection should move along with it. Currently, the editor does not do this; it only moves the one node. I think it's more intuitive to have the entire selection move, in which case, having the node being dragged become the selected node after the mouse is release makes a bit more sense to me. Otherwise, if a bunch of things are selected and moved, maybe the selection shouldn't change at all after the mouse is released.

**Comment by RighteousRaichu** [comment]
I agree that the whole selection should move. And to keep consistent maybe we should just have moving an element not change the selection at all? (Currently it does.)

**Comment by ilargierdi** [comment]
I think that makes the most sense. I'm going to make the change tonight and close this issue if you agree.

**Comment by RighteousRaichu** [comment]
Sounds good.

**Comment by ilargierdi** [comment]
Closing the issue. The editor now moves all selected nodes in sync. If nothing is selected while dragging anything, the drag object is then selected; otherwise, if anything else is selected, whatever is being dragged does not get set as the selected object.
