### ISSUE TITLE
Why is modal-window.ts in the models folder?

### ISSUE THREAD

**Issue by ilargierdi** [2graphic/sinap-ide#99]
Title.

**Comment by RighteousRaichu** [comment]
Basically models is the miscellaneous non-angular specific folder for our project. It exports an interface that a service can implement if it wants to provide modal windows. The modal-windows folder is a mini angular project that's used with our ModalService.service.ts that implement ModalService.

Now that I'm thinking about it too much, modal-window.ts should probably be renamed modal.ts because not all modals need to be windows.

**Comment by Sheyne** [comment]
Should we close this?

**Comment by ilargierdi** [comment]
Up to @RighteousRaichu. I'm not sure if he wants to rename modal-window.ts.

**Comment by RighteousRaichu** [comment]
Might revisit naming when I revisit this stuff and make it performant.
